export interface Memory {
  id: string;
  title: string;
  date: string;
  description: string;
  imageUrl: string; // Keep for backward compatibility
  images?: string[]; // New: support multiple images
  location: string;
  tags: string[];
  aiNarrative?: string; // Generated by Gemini
  mood?: 'happy' | 'romantic' | 'adventure' | 'cozy';
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  timestamp: number;
}

export interface DashboardStats {
  totalPhotos: number;
  citiesVisited: number;
  daysTogether: number;
  monthlyActivity: { month: string; count: number }[];
  categories: { name: string; value: number }[];
}

export interface Flower {
  id: string;
  imageUrl: string;
  date: string;
  note: string; // 表白语
}

export interface Snack {
  id: string;
  imageUrl: string;
  date: string;
  name: string; // 零食名称
  rating: number; // 评分 1-5
  note?: string; // 新增：评价/备注
}

export interface CityVisit {
  id: string;
  city: string;
  date: string;
  imageUrl?: string; // Keep for backward compatibility
  images?: string[]; // New: support multiple images
  notes: string;
}

export interface SpecialDate {
  id: string;
  title: string;
  date: string; // YYYY-MM-DD
  type: 'birthday' | 'anniversary' | 'other';
}

export interface SocialPost {
  id: string;
  platform: 'douyin' | 'weibo';
  url: string;
  title: string;
  coverImage?: string;
  screenshot?: string; // Base64 encoded screenshot
  date: string;
  description?: string;
}

export interface Photo {
  id: string;
  imageUrl: string;
  category: 'ccd' | 'camera' | 'phone' | 'pocket3';
  date: string;
  note?: string;
}

export interface TodoItem {
  id: string;
  text: string;
  completed: boolean;
}

export enum AppView {
  TIMELINE = 'TIMELINE',
  DASHBOARD = 'DASHBOARD',
  CHAT = 'CHAT',
  MAP = 'MAP', // 现在作为旅行打卡页
  FLOWER_WALL = 'FLOWER_WALL',
  SNACK_WALL = 'SNACK_WALL',
  TODO_LIST = 'TODO_LIST',
  ANNIVERSARY = 'ANNIVERSARY',
  SOCIAL_MEDIA = 'SOCIAL_MEDIA',
  PHOTO_GALLERY = 'PHOTO_GALLERY' // 美丽欧欧照片墙
}